# Test BORRARRRR
# ###########################################
gestorgetpaises:
    path:
        en:   /gestor/getpaises
        es:   /gestor/getpaises
    methods:    GET|POST
    controller: App\Controller\TestController::getPaises
gestorgetProvincias:
    path:
        en:   /gestor/getProvincias
        es:   /gestor/getProvincias
    methods:    GET|POST
    controller: App\Controller\TestController::getProvincias
gestorgetIdiomas:
    path:
        en:   /gestor/getIdiomas
        es:   /gestor/getIdiomas
    methods:    GET|POST
    controller: App\Controller\TestController::getIdiomas
gestorgetAreasInteres:
    path:
        en:   /gestor/getAreasInteres
        es:   /gestor/getAreasInteres
    methods:    GET|POST
    controller: App\Controller\TestController::getAreasInteres
gestorgetOficinas:
    path:
        en:   /gestor/getOficinas
        es:   /gestor/getOficinas
    methods:    GET|POST
    controller: App\Controller\TestController::getOficinas
gestorgetSecretarias:
    path:
        en:   /gestor/getSecretarias
        es:   /gestor/getSecretarias
    methods:    GET|POST
    controller: App\Controller\TestController::getSecretarias
gestorgetResponsablesMarketing:
    path:
        en:   /gestor/getResponsablesMarketing
        es:   /gestor/getResponsablesMarketing
    methods:    GET|POST
    controller: App\Controller\TestController::getResponsablesMarketing
gestorgetSociosResponsables:
    path:
        en:   /gestor/getSociosResponsables
        es:   /gestor/getSociosResponsables
    methods:    GET|POST
    controller: App\Controller\TestController::getSociosResponsables
gestorgetContactoWebtForm:
    path:
        en:   /gestor/getContactoWebtForm
        es:   /gestor/getContactoWebtForm
    methods:    GET|POST
    controller: App\Controller\TestController::getContactoWebtForm

# TEMPORAL (BORRAR)
##############################################
productDetailServices:
    path:
        en:   /product-service
        es:   /producto-servicio
        pt:   /product-service
        ge:   /product-service
    methods:    GET|POST
    controller: App\Controller\Web\ServicesController::productDetailServices

fiscal:
    path:
        en:   /fiscal
        es:   /fiscal
        pt:   /fiscal
        ge:   /fiscal
    methods:    GET|POST
    controller: App\Controller\Web\ServicesController::fiscal

events_detail2:
   path:
       en:   /event
       es:   /evento
       pt:   /event
       ge:   /event
   methods:    GET|POST
   controller: App\Controller\Web\KnowledgeController::detail2

# HOME
# ###########################################
home:
    path:
        en:   /
        es:   /
        pt:   /
    methods:    GET|POST
    controller: App\Controller\Web\HomeController::index

# USER
# ###########################################
userSettings:
    path:
        en:   /user-settings
        es:   /preferencias-usuario
        pt:   /user-settings
        ge:   /user-settings
    methods:    GET|POST
    controller: App\Controller\Web\UserController::newUser

# PRIVACY
# ###########################################
siteMap:
    path:
        en:   /site-map
        es:   /mapa-web
        pt:   /site-map
        ge:   /site-map
    methods:    GET|POST
    controller: App\Controller\Web\PrivacyController::siteMap

webUse:
    path:
        en:   /terms-of-use
        es:   /condiciones-de-uso
        pt:   /terms-of-use
        ge:   /terms-of-use
    methods:    GET|POST
    controller: App\Controller\Web\PrivacyController::webUse

privacyPolicy:
    path:
        en:   /privacy-policy
        es:   /politica-de-privacidad
        pt:   /privacy-policy
        ge:   /privacy-policy
    methods:    GET|POST
    controller: App\Controller\Web\PrivacyController::privacyPolicy

cookiesPolicy:
    path:
        en:   /cookies-policy
        es:   /politica-de-cookies
        pt:   /cookies-policy
        ge:   /cookies-policy
    methods:    GET|POST
    controller: App\Controller\Web\PrivacyController::cookiesPolicy

securityPolicy:
    path:
        en:   /information-security-policy
        es:   /politica-seguridad-informacion
        pt:   /information-security-policy
        ge:   /information-security-policy
    methods:    GET|POST
    controller: App\Controller\Web\PrivacyController::securityPolicy

contactUs:
    path:
        en:   /contact-us
        es:   /contacta
        pt:   /contact-us
        ge:   /contact-us
    methods:    GET|POST
    controller: App\Controller\Web\PrivacyController::contactUs

# KNOWLEDGE
# ###########################################
knowledge_index:
    path:
        en:   /knowledge
        es:   /conocimiento
        pt:   /knowledge
    methods:    GET|POST
    controller: App\Controller\Web\KnowledgeController::index

# SECTORS
# ###########################################
sectors_index:
    path:
        en:   /sectors
        es:   /sectores
        pt:   /sectors
    methods:    GET|POST
    controller: App\Controller\Web\SectorController::index

sectors_detail:
   path:
       en:   /sectors/{slug}
       es:   /sectores/{slug}
       pt:   /sectors/{slug}
       ge:   /sectores/{slug}
   methods:    GET|POST
   controller: App\Controller\Web\SectorController::detail

# CASES
# ###########################################
case_studies_detail:
    path:
        en:   /cases/{slug}
        es:   /casos/{slug}
        pt:   /cases/{slug}
        ge:   /cases/{slug}
    methods:    GET|POST
    controller: App\Controller\Web\CaseStudyController::detail

# SERVICES
# ###########################################
services_index:
    path:
        en:   /services
        es:   /servicios
        pt:   /services
    methods:    GET|POST
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: practices_index
        keepQueryParams: true

# PRACTICES
# ###########################################
practices_index:
    path:
        en:   /practice-areas
        es:   /areas-de-practica
        pt:   /practice-areas
    methods:    GET|POST
    controller: App\Controller\Web\PracticeController::index

practices_detail:
   path:
       en:   /practice-areas/{slug}
       es:   /areas-de-practica/{slug}
       pt:   /practice-areas/{slug}
       ge:   /practice-areas/{slug}
   methods:    GET|POST
   controller: App\Controller\Web\PracticeController::detail

# DESKS
# ###########################################
desks_index:
   path:
       en:   /desks
       es:   /desks
       pt:   /desks
   methods:    GET|POST
   controller: App\Controller\Web\DeskController::index

desks_detail:
   path:
       en:   /desks/{slug}
       es:   /desks/{slug}
       pt:   /desks/{slug}
       ge:   /desks/{slug}
   methods:    GET|POST
   controller: App\Controller\Web\DeskController::detail

# PRODUCTS
# ###########################################
products_index:
    path:
        en:   /other-services
        es:   /otros-servicios
        pt:   /other-services
    methods:    GET|POST
    controller: App\Controller\Web\ProductsController::index

products_detail:
   path:
       en:   /other-services/{slug}
       es:   /otros-servicios/{slug}
       pt:   /other-services/{slug}
       ge:   /other-services/{slug}
   methods:    GET|POST
   controller: App\Controller\Web\ProductsController::detail

# EVENTS
# ###########################################
events_directory:
   path:
       en:   /events
       es:   /eventos
       pt:   /events
   methods:      GET
   controller:   App\Controller\Web\EventController::index

events_detail:
   path:
       en:   /events/{slug}
       es:   /eventos/{slug}
       pt:   /events/{slug}
       ge:   /events/{slug}
   methods:    GET|POST
   controller: App\Controller\Web\EventController::detail

get_events:
   path:
       en:   /get_events_ajax
       es:   /get_events_ajax
       pt:   /get_events_ajax
       ge:   /get_events_ajax
   methods:    GET|POST
   controller: App\Controller\Web\EventController::ajaxActionEvent

set_event_contact:
   path:
       en:   /set_contact_ajax
       es:   /set_contact_ajax
       pt:   /set_contact_ajax
       ge:   /set_contact_ajax
   methods:    GET|POST
   controller: App\Controller\Web\EventController::ajaxActionContact

set_contact_user:
   path:
       en:   /set_contact_ajax_WS
       es:   /set_contact_ajax_WS
       pt:   /set_contact_ajax_WS
       ge:   /set_contact_ajax_WS
   methods:    GET|POST
   controller: App\Controller\Web\UserController::ajaxActionContact

get_regions:
   path:
       en:   /get_regions
       es:   /get_regions
       pt:   /get_regions
       ge:   /get_regions
   methods:    GET|POST
   controller: App\Controller\Web\EventController::ajaxActionRegions

# LAWYERS
# ###########################################
lawyers_index:
    path:
        en:     /lawyers
        es:     /abogados
        pt:     /lawyers
    methods:      GET
    controller:   App\Controller\Web\LawyerController::index

lawyers_detail:
    path:
        en:     /lawyers/{slug}
        es:     /abogados/{slug}
        pt:     /lawyers/{slug}
        ge:     /lawyers/{slug}
    methods:    GET|POST
    controller: App\Controller\Web\LawyerController::detail

lawyers_vcard_download:
    path:
        en:   /lawyers/{id}/download/
        es:   /abogados/{id}/descarga
        pt:   /lawyers/{id}/download/
        ge:   /lawyers/{id}/download/
    methods:    GET|POST
    controller: App\Controller\Web\LawyerController::download

# INSIGHTS
# ###########################################
insights_index:
    path:
        en:   /insights
        es:   /insights
        pt:   /insights
    methods:    GET|POST
    controller: App\Controller\Web\InsightController::index

insights_detail:
    path:
        en:     /insights/{slug}
        es:     /insights/{slug}
        pt:     /insights/{slug}
        ge:     /insights/{slug}
    methods:    GET|POST
    controller: App\Controller\Web\InsightController::detail

# OFFICES
# ###########################################
offices_detail:
    path:
        en:     /offices/{slug}
        es:     /oficinas/{slug}
        pt:     /offices/{slug}
        ge:     /offices/{slug}
    methods:    GET|POST
    controller: App\Controller\Web\OfficeController::detail

# PAGES
# ###########################################
pages_detail:
    path:
        en:     /p/{slug}
        es:     /p/{slug}
        pt:     /p/{slug}
        ge:     /p/{slug}
    methods:    GET|POST
    controller: App\Controller\Web\PagesController::detail

# PUBLICATIONS
# ###########################################
publications_detail:
    path:
        en:   /article/{slug}
        es:   /articulo/{slug}
        pt:   /article/{slug}
        ge:   /article/{slug}
    methods:    GET|POST
    controller: App\Controller\Web\PublicationController::detail

# API-PUBLICATIONS
##############################################
publications-api:
    path:
        en:   /publications-api/posts
        es:   /publications-api/posts
    methods:    GET|POST
    controller: App\Controller\APIController::posts

publications-api-media:
    path:
        en:   /publications-api/media
        es:   /publications-api/media
    methods:    GET|POST
    controller: App\Controller\APIController::media

# PAGES REGIONS
# ###########################################
location:
    path:
        en:   /location
        es:   /location
        pt:   /location
        ge:   /location
    methods:    GET|POST
    controller: App\Controller\Web\LocationController::index

location_detail:
    path:
        en:   /location/{slug}
        es:   /location/{slug}
        pt:   /location/{slug}
        ge:   /location/{slug}
    methods:    GET|POST
    controller: App\Controller\Web\LocationController::detail

location_other:
    path:
        en:   /locationother
        es:   /locationother
        pt:   /locationother
        ge:   /locationother
    methods:    GET|POST
    controller: App\Controller\Web\LocationController::indexOther

location_other_detail:
    path:
        en:   /locationother/{slug}
        es:   /locationother/{slug}
        pt:   /locationother/{slug}
        ge:   /locationother/{slug}
    methods:    GET|POST
    controller: App\Controller\Web\LocationController::detailOther

# PAGES FIRM
# ###########################################

firm:
    path:
        es:   /firm/{slug}
        en:   /firm/{slug}
        pt:   /firm/{slug}
        ge:   /firm/{slug}
    methods:    GET|POST
    controller: App\Controller\Web\PagesController::detail

# PAGES TALENT ( EX CAREER )
##############################################
talent:
    path:
        es:   /talent/{slug}
        en:   /talent/{slug}
        pt:   /talent/{slug}
        ge:   /talent/{slug}
    methods:    GET|POST
    controller: App\Controller\Web\PagesController::detail

# PAGES international organizations
##############################################
organization:
    path:
        es:   /organization/{slug}
        en:   /organization/{slug}
        pt:   /organization/{slug}
        ge:   /organization/{slug}
    methods:    GET|POST
    controller: App\Controller\Web\PagesController::detail

# BRANDS
# Temporal, mantener hasta nueva fase del proyecto
# ###########################################
institutoRRHH:
    path:
        en:   /instituto-estrategia-legal-rrhh
        es:   /instituto-estrategia-legal-rrhh
        pt:   /instituto-estrategia-legal-rrhh
        ge:   /instituto-estrategia-legal-rrhh
    methods:    GET|POST
    controller: App\Controller\Web\BrandsController::institutoRRHH

# COMPONENTES
# No tocar, es una maqueta de referencia que no necesita programaci√≥n
# ###########################################
components:
    path:
        en:   /components
        es:   /componentes
        pt:   /components
        ge:   /componentes
    methods:    GET|POST
    controller: App\Controller\Web\ComponentsController::index
